# Generated by Django 4.1.2 on 2022-11-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='123 4567 890', max_length=15),
            preserve_default=False,
        ),
    ]
