# Generated by Django 4.1.2 on 2022-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0003_remove_suggested_levels_max_protein_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='k',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='phos',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
