# Generated by Django 4.1.2 on 2022-12-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0004_alter_food_k_alter_food_phos_alter_food_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entries',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthtracker.user'),
            preserve_default=False,
        ),
    ]
