# Generated by Django 4.1.2 on 2022-12-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0005_journal_entries_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entries',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
